version: '2.0'
services:

  webgateway:
    build:
      context: webgateway
    container_name: webgateway
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./webgateway/CSP.ini:/opt/webgateway/bin/CSP.ini

  iris:
    container_name: iris
    build:
      context: iris
      args:
        IRIS_PASSWORD: "${IRIS_PASSWORD}"
    ports:
      - 52773:52773
      - 51773:51773
    volumes:
      - ./shared:/shared

  # java gateway
  jgw:
    image: intersystemscommunity/jgw:latest
    container_name: jgw
    restart: always
    ports: 
      - 55555:55555
    volumes:
      - ./java/target/iris-google-oauth-pex-0.1-jar-with-dependencies.jar:/jgw/iris-google-oauth-pex-0.1-jar-with-dependencies.jar
      - ./google-credentials.json:/credentials/google-credentials.json
