/// 
Class Chatbot.BP.DialogFlowWebHookProcess Extends Ens.BusinessProcessBPL
{

/// BPL Definition.
XData BPLError [ XMLNamespace = "http://www.intersystems.com/bpl" ]
{
<diagram Name="Chatbot.BP.DialogFlowWebHookProcess" HasErrors="1" Language="objectscript" ContextSuperClass="" Layout="automatic" Version="" Includes="" Request="Ens.Request" Response="Ens.Response" Width="2000" Height="2000" ShowAnnotation="1">
<shape _Type="start" Name="" xPos="200" yPos="150" _index="0"/>
<shape _Type="end" Name="" xPos="200" yPos="250" _index="1"/>
</diagram>
}

}
